//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRDemo2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public long ID { get; set; }
        public long Пользователь { get; set; }
        public System.DateTime ДатаВремяЗвонкаПоЛиду { get; set; }
        public int ДлительностьЗвонка { get; set; }
        public long Лид { get; set; }
        public bool Удален { get; set; }
        public string Коментарий { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual User User { get; set; }
    }
}
