//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRDemo2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.Call = new HashSet<Call>();
        }
    
        public long ID { get; set; }
        public long Логин { get; set; }
        public decimal РаботаСВозражениями { get; set; }
        public decimal ОвладениеНавыкамиПродаж { get; set; }
        public decimal ЗнаниеПродуктовКомпании { get; set; }
        public System.DateTime ДатаВремяСозданияЛида { get; set; }
        public long Статус { get; set; }
        public long НомерТелефонаКлиента { get; set; }
        public bool Удален { get; set; }
        public string Коментарий { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Call> Call { get; set; }
        public virtual CategoryLead CategoryLead { get; set; }
        public virtual User User { get; set; }
    }
}
